--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      yisslu
-- Project :      ModuloServicio.DM1
-- Author :       yisslu
--
-- Date Created : Sunday, December 03, 2023 22:28:03
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: DISTRIBUIDORES 
--

CREATE TABLE DISTRIBUIDORES(
    DISTRIBUIDORES_ID         NUMBER(10, 0)    NOT NULL,
    DIRECCION_DISTRIBUIDOR    VARCHAR2(50)     NOT NULL,
    DESCRIPCION               VARCHAR2(100)    NOT NULL,
    NOMBRE_DISTRIBUIDOR       VARCHAR2(25)     NOT NULL,
    CONSTRAINT DISTRIBUIDORES_PK PRIMARY KEY (DISTRIBUIDORES_ID)
)
;



-- 
-- TABLE: SERVICIO_CONTRATADO_STATUS 
--

CREATE TABLE SERVICIO_CONTRATADO_STATUS(
    SERVICIO_CONTRATADO_STATUS    NUMBER(10, 0)    NOT NULL,
    CLAVE                         VARCHAR2(15)     NOT NULL,
    DESCRIPCION                   VARCHAR2(100)    NOT NULL,
    CONSTRAINT SERV_CONTRATADO_STATUS_PK PRIMARY KEY (SERVICIO_CONTRATADO_STATUS)
)
;



-- 
-- TABLE: MARCA 
--

CREATE TABLE MARCA(
    MARCA_ID        NUMBER(10, 0)    NOT NULL,
    LOGO_MARCA      BLOB             NOT NULL,
    NOMBRE_MARCA    VARCHAR2(25)     NOT NULL,
    CONSTRAINT MARCA_PK PRIMARY KEY (MARCA_ID)
)
;



-- 
-- TABLE: MATERIALES 
--

CREATE TABLE MATERIALES(
    MATERIAL_ID          NUMBER(10, 0)    NOT NULL,
    PRECIO               NUMBER(8, 2)     NOT NULL,
    DESCRIPCION          VARCHAR2(100)    NOT NULL,
    DISTRIBUIDORES_ID    NUMBER(10, 0)    NOT NULL,
    MARCA_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT MATERIALES_PK PRIMARY KEY (MATERIAL_ID), 
    CONSTRAINT MATERIALES_DISTRIBUIDORES_ID_FK FOREIGN KEY (DISTRIBUIDORES_ID)
    REFERENCES DISTRIBUIDORES(DISTRIBUIDORES_ID),
    CONSTRAINT MATERIALES_MARCA_ID_FK FOREIGN KEY (MARCA_ID)
    REFERENCES MARCA(MARCA_ID)
)
;



-- 
-- TABLE: SERVICIO 
--

CREATE TABLE SERVICIO(
    SERVICIO_ID                   NUMBER(10, 0)     NOT NULL,
    FECHA_STATUS                  DATE              NOT NULL,
    FECHA_SERVICIO                DATE              NOT NULL,
    DESCRIPCION                   VARCHAR2(1000)    NOT NULL,
    DESCRIPCION_PDF               BLOB              NOT NULL,
    PROVEEDOR_SERVICIO_ID         NUMBER(10, 1)     NOT NULL,
    CLIENTE_ID                    NUMBER(10, 0)     NOT NULL,
    SERVICIO_CONTRATADO_STATUS    NUMBER(10, 0)     NOT NULL,
    PRECIO                        NUMBER(7, 2),
    INSTRUCCIONES_ACEPTADO        VARCHAR2(1000),
    MENSUALIDADES                 NUMBER(2, 0),
    MATERIAL_ID                   NUMBER(10, 0)     NOT NULL,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (SERVICIO_ID), 
    CONSTRAINT SERVICIO_CONTRATADO_STATUS_FK FOREIGN KEY (SERVICIO_CONTRATADO_STATUS)
    REFERENCES SERVICIO_CONTRATADO_STATUS(SERVICIO_CONTRATADO_STATUS),
    CONSTRAINT SERVICIO_MATERIAL_ID_FK FOREIGN KEY (MATERIAL_ID)
    REFERENCES MATERIALES(MATERIAL_ID)
)
;



-- 
-- TABLE: EVIDENCIA 
--

CREATE TABLE EVIDENCIA(
    EVIDENCIA_ID         NUMBER(10, 0)    NOT NULL,
    DESCRIPCION          VARCHAR2(300)    NOT NULL,
    FECHA_ELABORACION    DATE             NOT NULL,
    SERVICIO_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EVIDENCIA_PK PRIMARY KEY (EVIDENCIA_ID), 
    CONSTRAINT EVIDENCIA_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
)
;



-- 
-- TABLE: HISTORICO_SERVICIO_STATUS 
--

CREATE TABLE HISTORICO_SERVICIO_STATUS(
    HISTORICO_SERVICIO_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                    DATE             NOT NULL,
    SERVICIO_ID                     NUMBER(10, 0)    NOT NULL,
    SERVICIO_CONTRATADO_STATUS      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_SERV_STATUS_PK PRIMARY KEY (HISTORICO_SERVICIO_STATUS_ID), 
    CONSTRAINT HISTORICO_SERV_STATUS_SERV_FK FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID),
    CONSTRAINT HISTORICO_SER_CONTRATADO_STATUS_FK FOREIGN KEY (SERVICIO_CONTRATADO_STATUS)
    REFERENCES SERVICIO_CONTRATADO_STATUS(SERVICIO_CONTRATADO_STATUS)
)
;



-- 
-- TABLE: SERVICIO_EVIDENCIA_FOTO 
--

CREATE TABLE SERVICIO_EVIDENCIA_FOTO(
    EVIDENCIA_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    FOTO            BLOB             NOT NULL,
    CONSTRAINT SERV_EVIDENCIA_FOTO_PK PRIMARY KEY (EVIDENCIA_ID), 
    CONSTRAINT SERV_EVIDENCIA_FOTO_EVIDENCIA_FK FOREIGN KEY (EVIDENCIA_ID)
    REFERENCES EVIDENCIA(EVIDENCIA_ID)
)
;



