--

-- ER/Studio 8.0 SQL Code Generation

-- Company :      UNAM

-- Project :      HouseServices.DM1

-- Author :       Giovanni Chavez

--

-- Date Created : Sunday, December 03, 2023 23:32:11

-- Target DBMS : Oracle 11g

--



-- 

-- TABLE: BANCO 

--



CREATE TABLE BANCO(

    BANCO_ID        NUMBER(100, 0)    NOT NULL,

    NOMBRE_BANCO    VARCHAR2(50)      NOT NULL,

    CONSTRAINT BANCO_PK PRIMARY KEY (BANCO_ID)

);







-- 

-- TABLE: ENTIDAD 

--



CREATE TABLE ENTIDAD(

    ENTIDAD_ID    NUMBER(10, 0)    NOT NULL,

    NOMBRE        VARCHAR2(25)     NOT NULL,

    CONSTRAINT ENTIDAD_PK PRIMARY KEY (ENTIDAD_ID)

)

;







-- 

-- TABLE: STATUS_PROVEEDOR 

--



CREATE TABLE STATUS_PROVEEDOR(

    STATUS_PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,

    CLAVE                  VARCHAR2(20)     NOT NULL,

    DESCRIPCION            VARCHAR2(200)    NOT NULL,

    CONSTRAINT STATUS_PROVEEDOR_PK PRIMARY KEY (STATUS_PROVEEDOR_ID)

);







-- 

-- TABLE: ESTUDIO 

--



CREATE TABLE ESTUDIO(

    ESTUDIO_ID        NUMBER(10, 0)    NOT NULL,

    NIVEL_ESTUDIOS    VARCHAR2(10)     NOT NULL,

    CONSTRAINT ESTUDIO_PK PRIMARY KEY (ESTUDIO_ID)

)

;







-- 

-- TABLE: PROVEEDOR 

--



CREATE TABLE PROVEEDOR(

    PROVEEDOR_ID           NUMBER(10, 1)     NOT NULL,

    FECHA_STATUS           DATE              NOT NULL,

    NOMBRE                 VARCHAR2(20)      NOT NULL,

    AP_PATERNO             VARCHAR2(15)      NOT NULL,

    AP_MATERNO             VARCHAR2(10),

    FOTO                   BLOB              NOT NULL,

    FECHA_NAC              DATE              NOT NULL,

    DIRECCION              VARCHAR2(100)     NOT NULL,

    TELEFONO_CASA          NUMBER(10, 10)    NOT NULL,

    TELEFONO_MOVIL         NUMBER(10, 10)    NOT NULL,

    ENTIDAD_ID             NUMBER(10, 0)     NOT NULL,

    STATUS_PROVEEDOR_ID    NUMBER(10, 0)     NOT NULL,

    ESTUDIO_ID             NUMBER(10, 0)     NOT NULL,

    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (PROVEEDOR_ID), 

    CONSTRAINT PROVEEDOR_ENTIDAD_ID_FK FOREIGN KEY (ENTIDAD_ID)

    REFERENCES ENTIDAD(ENTIDAD_ID),

    CONSTRAINT PROVEEDOR_STATUS_PROVEEDOR_ID_FK FOREIGN KEY (STATUS_PROVEEDOR_ID)

    REFERENCES STATUS_PROVEEDOR(STATUS_PROVEEDOR_ID),

    CONSTRAINT PROVEEDOR_ESTUDIO_ID_FK FOREIGN KEY (ESTUDIO_ID)

    REFERENCES ESTUDIO(ESTUDIO_ID)

);







-- 

-- TABLE: DOCUMENTO_PROVEEDOR 

--



CREATE TABLE DOCUMENTO_PROVEEDOR(

    DOCUMENTO_PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,

    IDENTIFICACION            BLOB             NOT NULL,

    COMPROBANTE_DOMICILIO     BLOB             NOT NULL,

    PROVEEDOR_ID              NUMBER(10, 1)    NOT NULL,

    CONSTRAINT DOCUMENTO_PROVEEDOR_PK PRIMARY KEY (DOCUMENTO_PROVEEDOR_ID), 

    CONSTRAINT DOCUMENTO_PROVEEDOR_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)

    REFERENCES PROVEEDOR(PROVEEDOR_ID)

);







-- 

-- TABLE: CUENTA_BANCARIA_PROVEEDOR 

--



CREATE TABLE CUENTA_BANCARIA_PROVEEDOR(

    DOCUMENTO_PROVEEDOR_ID    NUMBER(10, 0)     NOT NULL,

    CUENTA_CLABE              VARCHAR2(16)      NOT NULL,

    BANCO_ID                  NUMBER(100, 0)    NOT NULL,

    CONSTRAINT CUENTA_BANCARIA_PROVEEDOR_PK PRIMARY KEY (DOCUMENTO_PROVEEDOR_ID), 

    CONSTRAINT CUENTA_BANCARIA_PROVEEDOR_DOCUMENTO_PROVEEDOR_ID_FK FOREIGN KEY (DOCUMENTO_PROVEEDOR_ID)

    REFERENCES DOCUMENTO_PROVEEDOR(DOCUMENTO_PROVEEDOR_ID),

    CONSTRAINT CUENTA_BANCARIA_PROVEEDOR_BANCO_ID_FK FOREIGN KEY (BANCO_ID)

    REFERENCES BANCO(BANCO_ID)

);







-- 

-- TABLE: TIPO_SERVICIO 

--



CREATE TABLE TIPO_SERVICIO(

    TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,

    NOMBRE              VARCHAR2(20)     NOT NULL,

    DESCRIPCION         VARCHAR2(100)    NOT NULL,

    CONSTRAINT TIPO_SERVICIO_PK PRIMARY KEY (TIPO_SERVICIO_ID)

)

;







-- 

-- TABLE: PROVEEDOR_SERVICIO 

--



CREATE TABLE PROVEEDOR_SERVICIO(

    PROVEEDOR_SERVICIO_ID    NUMBER(10, 1)    NOT NULL,

    ANIOS_EXPERIENCIA        NUMBER(2, 0)     NOT NULL,

    PROVEEDOR_ID             NUMBER(10, 1)    NOT NULL,

    TIPO_SERVICIO_ID         NUMBER(10, 0)    NOT NULL,

    CONSTRAINT PROVEEDOR_SERVICIO_PK PRIMARY KEY (PROVEEDOR_SERVICIO_ID), 

    CONSTRAINT PROVEEDOR_SERVICIO_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)

    REFERENCES PROVEEDOR(PROVEEDOR_ID),

    CONSTRAINT PROVEEDOR_SERVICIO_TIPO_SERVICIO_FK FOREIGN KEY (TIPO_SERVICIO_ID)

    REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID)

);







-- 

-- TABLE: DOCUMENTO_EXPERIENCIA 

--



CREATE TABLE DOCUMENTO_EXPERIENCIA(

    DOCUMENTO_EXPERIENCIA_ID    NUMBER(10, 0)    NOT NULL,

    DOCUMENTO                   BLOB             NOT NULL,

    PROVEEDOR_SERVICIO_ID       NUMBER(10, 1)    NOT NULL,

    TIPO                        VARCHAR2(15)     NOT NULL,

    CONSTRAINT DOCUMENTO_EXPERIENCIA_PK PRIMARY KEY (DOCUMENTO_EXPERIENCIA_ID), 

    CONSTRAINT DOCUMENTO_EXPERIENCIA_PROVEEDOR_SERVICIO_FK FOREIGN KEY (PROVEEDOR_SERVICIO_ID)

    REFERENCES PROVEEDOR_SERVICIO(PROVEEDOR_SERVICIO_ID)

);







-- 

-- TABLE: EMAIL 

--



CREATE TABLE EMAIL(

    EMAIL_ID        NUMBER(10, 0)    NOT NULL,

    CORREO          VARCHAR2(25)     NOT NULL,

    PROVEEDOR_ID    NUMBER(10, 1)    NOT NULL,

    CONSTRAINT EMAIL_PK PRIMARY KEY (EMAIL_ID), 

    CONSTRAINT EMAIL_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)

    REFERENCES PROVEEDOR(PROVEEDOR_ID)

);







-- 

-- TABLE: HISTORICO_STATUS_PROVEEDOR 

--



CREATE TABLE HISTORICO_STATUS_PROVEEDOR(

    HISTORICO_STATUS_PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,

    FECHA_STATUS                     DATE             NOT NULL,

    STATUS_PROVEEDOR_ID              NUMBER(10, 0)    NOT NULL,

    PROVEEDOR_ID                     NUMBER(10, 1)    NOT NULL,

    CONSTRAINT HISTORICO_STATUS_PROVEEDOR_PK PRIMARY KEY (HISTORICO_STATUS_PROVEEDOR_ID), 

    CONSTRAINT HISTORICO_STATUS_PROVEEDOR_STATUS_PROVEEDOR_ID_FK FOREIGN KEY (STATUS_PROVEEDOR_ID)

    REFERENCES STATUS_PROVEEDOR(STATUS_PROVEEDOR_ID),

    CONSTRAINT HISTORICO_STATUS_PROVEEDOR_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)

    REFERENCES PROVEEDOR(PROVEEDOR_ID)

);







-- 

-- TABLE: PAGO 

--



CREATE TABLE PAGO(

    PAGO_ID         NUMBER(10, 0)    NOT NULL,

    PROVEEDOR_ID    NUMBER(10, 1),

    COMPROBANTE     BLOB             NOT NULL,

    FECHA           DATE             NOT NULL,

    MONTO           NUMBER(7, 2)     NOT NULL,

    CLABE           VARCHAR2(18)     NOT NULL,

    CONSTRAINT PAGO_PK PRIMARY KEY (PAGO_ID), 

    CONSTRAINT PAGO_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)

    REFERENCES PROVEEDOR(PROVEEDOR_ID)

);







