--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      Ana Fragoso
-- Project :      modeloCliente.DM1
-- Author :       Ana Fragoso
--
-- Date Created : Monday, December 04, 2023 14:48:00
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE_ID        NUMBER(10, 0)    NOT NULL,
    USERNAME          VARCHAR2(25)     NOT NULL,
    EMAIL             VARCHAR2(30)     NOT NULL,
    CONTRASENIA       VARCHAR2(20)     NOT NULL,
    DIRECCION         VARCHAR2(100)    NOT NULL,
    TELEFONO          NUMBER(10, 0)    NOT NULL,
    TIPO              CHAR(1)          NOT NULL,
    FECHA_REGISTRO    DATE             NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: EMPRESA 
--

CREATE TABLE EMPRESA(
    CLIENTE_ID       NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(30)     NOT NULL,
    DESCRIPCION      VARCHAR2(150)    NOT NULL,
    LOGOTIPO         BLOB             NOT NULL,
    NUM_EMPLEADOS    NUMBER(4, 0)     NOT NULL,
    CONSTRAINT EMPRESA_PK PRIMARY KEY (CLIENTE_ID), 
    CONSTRAINT CLIENTE_EMPRESA_FK FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: PERSONA 
--

CREATE TABLE PERSONA(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(30)     NOT NULL,
    FOTO                BLOB             NOT NULL,
    CURP                VARCHAR2(16)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    CONSTRAINT PERSONA_PK PRIMARY KEY (CLIENTE_ID), 
    CONSTRAINT CLIENTE_PERSONA_FK FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: SERVICIO_EVALUACION 
--

CREATE TABLE SERVICIO_EVALUACION(
    SERVICIO_EVALUACION_ID    NUMBER(10, 0)    NOT NULL,
    COMENTARIO                VARCHAR2(300)    NOT NULL,
    CALIFICACION              NUMBER(1, 0)     NOT NULL,
    CLIENTE_ID                NUMBER(10, 0)    NOT NULL,
    SERVICIO_EXT_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT SERVICIO_EVALUACION_PK PRIMARY KEY (SERVICIO_EVALUACION_ID), 
    CONSTRAINT EVALUACION_CLIENTEID_FK FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    TARJETA_ID        NUMBER(10, 0)     NOT NULL,
    NUMERO_TARJETA    VARCHAR2(16)      NOT NULL,
    CVV               VARCHAR2(3)       NOT NULL,
    CLIENTE_ID        NUMBER(10, 0)     NOT NULL,
    BANCO_EXT_ID      NUMBER(100, 0)    NOT NULL,
    CONSTRAINT TARJETA_PK PRIMARY KEY (TARJETA_ID), 
    CONSTRAINT TARJETA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- ///////////////////////////////////////////////

